### PR TITLE
Feat potion generation

### LINKED ISSUE #8: Potion Generation and Falling
Add potion generation and falling within some sort of radius of the player every x seconds

### PR DESCRIPTION
**Pull request by rafiiary**
Generate and drop potion in front of the player from a certain height. Potion will also play particle effects when it hits the player.

### CODE REVIEW

**Comment by evank28** [comment]
I think the potion falling might be too fast. You can't really see the potion falling, just a big explosion.

**Comment by rafiiary** [comment]
> I think the potion falling might be too fast. You can't really see the potion falling, just a big explosion.

That's interesting, I only use gravity on the potion and don't add any sort of acceleration on it. Do you suggest I do otherwise?

**Comment by evank28** [comment]
I guess I would suggest we slow down the falling of the potion, since right now we can't see the vials falling. Maybe we should also have the potions fall *in front* (and not on-top) of the player's position and slowly, but with a blast radius, so players could see them fall and would have to avoid them. then, if they are too close to the exploding potion, they will still have a transformation.

**Comment by rafiiary** [comment]
> I guess I would suggest we slow down the falling of the potion, since right now we can't see the vials falling. Maybe we should also have the potions fall _in front_ (and not on-top) of the player's position and slowly, but with a blast radius, so players could see them fall and would have to avoid them. then, if they are too close to the exploding potion, they will still have a transformation.

I see what the problem is. I don't think you checked out my last commit. You must have looked at one of my earliest commits. In the last one, potions fall in front of you and you can actually see them falling for about 2 seconds.

**Comment by evank28** [comment]
I tried the latest commit and it still is not possible to see the actual potion fall in such a way that you could avoid it.

**Comment by evank28** [comment]
Ok latest meta files fixed it, because the spawn script is now linked the potion prefab.

**Pull request merged**
