### PR TITLE
Feat player swap

### PR DESCRIPTION
**Pull request by rafiiary**
Please take a look at the rotation of the blue sphere around the x axis when moving forwards or back. Player swap upon hitting potion works.

### CODE REVIEW

**Review by evank28 — CHANGES_REQUESTED** [review]
This looks good.

2 comments:
1. Why the changed camera angle? I like this new angle, but I would then want the camera to be closer to the player (to prevent obstructions from walls). But, the problem  with this angle is that you cannot see as much of the maze, which for a maze like this one, makes it a lot more difficult.
2. There seems to be a bug in this branch where after a certain number of transformations, the potions just stop spawning. Any idea why and can we fix this before merging please?

**Comment by kawaitenshi** [comment]
The transformation is working but if the player takes a potion and becomes blue inside the maze, the maze spins around and the movement buttons don't work as before. But when the player takes another potion and transforms back to red, it moves normally again and the walls stop spinning.
It seems to be fine outside the maze, only inside the maze it seems to happen, more specifically when the blue sphere touches the wall of the maze. If it doesn't touch the wall then it seems fine but once it touches the wall, things start spinning.
I also think the previous camera angle was better. I liked the camera angle from yesterday.

I noticed the y axis rotation is not frozen for Sphere2, once I freeze it it's fine.

**Comment by rafiiary** [comment]
> 

Fixed rotation issue.

**Comment by rafiiary** [comment]
> 
The camera angle change was arbitrary, I had lost the previous camera when I was working and had to create a new one to work with. I'll look at the old one and change it back.

**Comment by rafiiary** [comment]
> This looks good.
> 
> 2 comments:
> 
> 1. Why the changed camera angle? I like this new angle, but I would then want the camera to be closer to the player (to prevent obstructions from walls). But, the problem  with this angle is that you cannot see as much of the maze, which for a maze like this one, makes it a lot more difficult.
> 2. There seems to be a bug in this branch where after a certain number of transformations, the potions just stop spawning. Any idea why and can we fix this before merging please?

I've found the bug regarding your second comment. I will work on a solution before submitting for new review.

**Review by evank28 — APPROVED** [review]

**Pull request merged**
